### ISSUE TITLE
Plaintext password in file.

### ISSUE THREAD

**Issue by neenjaw** [spansh/edsm-export#1]
Hello @spansh!

Just trying to learn about your neutron star plotter and I found this repo to learn from your approach.  While looking through, I did notice that you have committed a plaintext password here: https://github.com/spansh/edsm-export/blob/dd1651b057290745070aeac9fa158c2b9ee8b079/export.pl#L179

This is for localhost connect, but it seems like this is a real password somewhere. Anyway, just a headsup!

**Comment by spansh** [comment]
Thanks very much for the heads up, I was made aware of it shortly after it
got uploaded.  As it was uploaded at any time and it was only a localhost
password I changed the relevant passwords quite some time back (even though
the database isn't exposed externally).

Always worth checking it though, so thankyou.
